/* AIFresourceInfo:com.crmimpl.aiftool.ClassDetails.type
 * This file is generated by the Amdocs data type generation utility on
 * Wed, 16 Oct 2013 18:49:51 IST. Do not edit this file by hand.
 *
 * ClassDetails.java
 *
 * Copyright (c) 1996 to 2009 Amdocs.  All rights reserved.
 *
 * These coded instructions, statements, and computer programs contain
 * unpublished trade secrets and proprietary information of Amdocs
 * and are protected by Federal copyright law and trade secret law.
 * They may not be disclosed to third parties or used or copied or
 * duplicated in any form, in whole or in part, without the prior
 * written consent of Amdocs.
 */

package com.crmimpl.aiftool;

  public class ClassDetails  implements com.amdocs.datatypes.DataType, java.io.Serializable, java.lang.Cloneable {

    private static final long serialVersionUID = 117944911809823L;
    public static final String JDK_VERSION = "5.0";


 

      private java.lang.String ParamName;
      private java.lang.String ParamType;

    /**
     * Default constructor.
     * Constructs a <tt> com.crmimpl.aiftool.ClassDetails </tt> object.
     */
    public ClassDetails(){
         super();
    }

    /**
     * @return value of "ParamName" field.
     */
      public java.lang.String getParamName() {
        return ParamName;
    }

    /**
     * @param value of "ParamName".
     */
      public void setParamName(java.lang.String value) {
        ParamName=value;
    }

    /**
     * @return value of "ParamType" field.
     */
      public java.lang.String getParamType() {
        return ParamType;
    }

    /**
     * @param value of "ParamType".
     */
      public void setParamType(java.lang.String value) {
        ParamType=value;
    }

        /**
         * Clone the object.
         * @return returns cloned object.
         */
          public Object clone()
    {
                try {
                        return super.clone();
                } catch (RuntimeException e) {
                        throw e;
                } catch (Exception e) {
                        throw new RuntimeException(e);
                }
        }


}
